apiVersion: v1
kind: Secret
metadata:
  name: chronos-secrets
  labels:
    app: chronos-os
type: Opaque
data:
  storage-dsn: {{ .Values.secrets.storageDSN | b64enc | quote }}
  {{- if .Values.secrets.apiKey }}
  api-key: {{ .Values.secrets.apiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.embeddingsKey }}
  embeddings-key: {{ .Values.secrets.embeddingsKey | b64enc | quote }}
  {{- end }}
