replicaCount: 2

image:
  repository: ghcr.io/spawn08/chronos
  tag: "0.1.0"

storage:
  backend: postgres

secrets:
  storageDSN: "postgres://chronos:changeme@postgres:5432/chronos?sslmode=disable"
  apiKey: ""
  embeddingsKey: ""

serviceAccount:
  create: true
  name: "chronos-os"
  annotations: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chronos.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilization: 70
  targetMemoryUtilization: 80
